### ISSUE TITLE
Incompatible java version

### ISSUE THREAD

**Issue by berndtj** [vmware/lightwave#22]
When installing lightwave server via `tdnf install vmware-lightwave-server`, jre 1.8.0.131 is installed:

```
root@ip-172-20-40-102 [ ~ ]# tdnf -y install vmware-lightwave-server

Installing:
...
openjre                                                    x86_64                1.8.0.131-1.ph1                            219.34 M
...
Complete!
```

This is not the expected version:

```
root@ip-172-20-40-102 [ ~ ]# export PATH=$PATH:/opt/vmware/bin:/opt/likewise/bin
root@ip-172-20-40-102 [ ~ ]# configure-lightwave-server --domain kops.bjung.net --password 'VMware!1' --hostname 34.210.152.203
Deploying in standalone mode...
/opt/vmware/bin/configure-lightwave-server: line 364: /var/opt/OpenJDK-1.8.0.112-bin/bin/java: No such file or directory
/opt/vmware/bin/configure-lightwave-server: line 386: /var/opt/OpenJDK-1.8.0.112-bin/bin/java: No such file or directory
PSC Installation failed.
```

I updated the scripts in /opt/vmware/bin and was able to continue.  Though this seems rather brittle.

**Comment by berndtj** [comment]
Solved this issue by first installing a very specific version of commons-daemon:

```
tdnf install -y commons-daemon-1.0.15-8.ph1 openjre-1.8.0.112 apache-tomcat-8.5.8
```

**Comment by balajiboggaram** [comment]
Hi Jung, 
Thank you for reporting. Lightwave is currently sticky on specific version of JAVA installation.We will consider addressing this issue.

**Comment by berndtj** [comment]
You don't need to rev the version, just fix the package to pull the specific version of commons-daemon.  As-is, the package is broken.

**Comment by phoenyx762** [comment]
Same issue with Photon 3 
lightwave-client-1.3.1.34-8.ph3.x86_64
apache-tomcat-8.5.51-4.ph3.noarch
lightwave-1.3.1.34-8.ph3.x86_64
openjre8-1.8.0.262-3.ph3.x86_64
commons-daemon-1.1.0-3.ph3.x86_64
apache-ant-1.10.8-1.ph3.noarch

-----Begin installing components-----
VMware Identity Manager
VMware Secure Token Service

Begin installing component: vmware-identity-manager
Installed vmware-identity-manager succesfully.

Begin installing component: vmware-secure-token-service
java.security.KeyStoreException: VKS not found
	at java.security.KeyStore.getInstance(KeyStore.java:851)
	at com.vmware.identity.configure.SecureTokenServerInstaller.getVksKeyStore(SecureTokenServerInstaller.java:205)
	at com.vmware.identity.configure.SecureTokenServerInstaller.checkSTSHealth(SecureTokenServerInstaller.java:132)
	at com.vmware.identity.configure.SecureTokenServerInstaller.install(SecureTokenServerInstaller.java:93)
	at com.vmware.identity.configure.VMIdentityController.setupInstance(VMIdentityController.java:117)
	at com.vmware.identity.configure.VMIdentityController.setupInstanceStandalone(VMIdentityController.java:29)
	at com.vmware.identity.configure.VMIdentityStandaloneInstaller.main(VMIdentityStandaloneInstaller.java:61)
Caused by: java.security.NoSuchAlgorithmException: VKS KeyStore not available
	at sun.security.jca.GetInstance.getInstance(GetInstance.java:159)
	at java.security.Security.getImpl(Security.java:695)
	at java.security.KeyStore.getInstance(KeyStore.java:848)
	... 6 more
VKS not found
vmware-secure-token-service installation failed.
Installation failed.
Errorcode: -1com.vmware.identity.configure.DomainControllerNativeException: java.security.KeyStoreException: VKS not found
	at com.vmware.identity.configure.VMIdentityController.setupInstance(VMIdentityController.java:127)
	at com.vmware.identity.configure.VMIdentityController.setupInstanceStandalone(VMIdentityController.java:29)
	at com.vmware.identity.configure.VMIdentityStandaloneInstaller.main(VMIdentityStandaloneInstaller.java:61)
Caused by: java.security.KeyStoreException: VKS not found
	at java.security.KeyStore.getInstance(KeyStore.java:851)
	at com.vmware.identity.configure.SecureTokenServerInstaller.getVksKeyStore(SecureTokenServerInstaller.java:205)
	at com.vmware.identity.configure.SecureTokenServerInstaller.checkSTSHealth(SecureTokenServerInstaller.java:132)
	at com.vmware.identity.configure.SecureTokenServerInstaller.install(SecureTokenServerInstaller.java:93)
	at com.vmware.identity.configure.VMIdentityController.setupInstance(VMIdentityController.java:117)
	... 2 more
Caused by: java.security.NoSuchAlgorithmException: VKS KeyStore not available
	at sun.security.jca.GetInstance.getInstance(GetInstance.java:159)
	at java.security.Security.getImpl(Security.java:695)
	at java.security.KeyStore.getInstance(KeyStore.java:848)
	... 6 more
Failed to start Secure Token Service.
Secure Token Service Installation - Failed

**Comment by snambakam** [comment]
The issue seems to be with the installation of openjre8 on Photon3 which is failing to update /etc/alternatives.

**Comment by phoenyx762** [comment]
Thanks for the reply!!! Do you believe updating to openjre10 or higher correct this issue? Since downgrading just does not seem to be an option.

**Comment by snambakam** [comment]
Unfortunately that does not help. Here is a temporary workaround while we fix the issue and submit a fix.
1. tdnf install -y lightwave
2. rpm -q --scripts openjre8 | grep -v postuninstall | grep -v posttrans > /tmp/test.sh
3. mv /etc/alternatives/jre/lib/ext /tmp
4. rm -rf /etc/alternatives/jre
5. bash /tmp/test.sh
6. mv /tmp/ext/*.jar /etc/alternatives/jre/lib/ext/
7. Edit /etc/hosts entries as per https://github.com/vmware/lightwave#set-up-the-hostname-for-the-instance
    Essentially, if the domain name is going to be lightwave.local and your hostname is photon-test, `hostname` should return photon-test and `hostname -f` should return photon-test.lightwave.local
8. /usr/bin/configure-lightwave-server --domain lightwave.local --password 'VMware123$'

**Comment by phoenyx762** [comment]
Thanks for the reply. The workaround the installation was successful this time. Now I am unable to access the web page as stated in step 5 (https://vmware.github.io/photon/assets/files/html/3.0/photon_installation/Installing-Lightwave-Server-and-Setting-Up-a-Domain.html) is there something else which I may be missing? I did add "--ssl-subject-alt-name <machine-ip-address>" to the end of the configure-lightwave-server command since I would need to add users and groups.
