### ISSUE TITLE
Error Promote Lightwave with Secure Token Service Installation - Failed

### ISSUE THREAD

**Issue by okehariansyah** [vmware/lightwave#29]
Hi,

I'm first time for Installing and promote vmware lightwave,  I found error after promoting lightwave about Secure Token Service installing failed

root@dc01 [ ~ ]# /opt/vmware/bin/configure-lightwave-server --domain domain.com --password **********
Deploying in standalone mode...
20180131040528:INFO:Setting up system as Infrastructure standalone node
20180131040528:INFO:Starting service [dcerpc]
20180131040528:INFO:Starting service [vmdns]
20180131040528:INFO:Starting service [vmafd]
20180131040530:INFO:Starting service [vmdir]
20180131040533:INFO:Starting service [vmca]
20180131040534:INFO:Setting various configuration values
20180131040535:INFO:Promoting directory service to be domain controller
20180131040602:INFO:Setting up the logical deployment unit
20180131040602:INFO:Setting up VMware Certificate Authority
20180131040602:INFO:Adding VMCA's root certificate to VMware endpoint certificate store
20180131040602:INFO:Generating Machine SSL cert
139639972570800:error:0906D06C:lib(9):func(109):reason(108):pem_lib.c:708:Expecting: CERTIFICATE
20180131040602:INFO:Setting Machine SSL certificate
20180131040602:INFO:Publishing Machine SSL certificate for directory service
20180131040602:INFO:Restarting service [vmdir]
Domain Controller setup was successful
Secure Token Service Installation - Started

-----Checking Authentication service-----
Authentication Service checked successfully.

-----Checking Directory service-----
Jan 31, 2018 4:06:07 AM com.vmware.identity.interop.ldap.OpenLdapClientLibrary <clinit>
INFO: SSL library initialized successfully
Directory Service checked successfully.

-----Checking Certificate service-----
Certificate Service checked successfully.
ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console. Set system property 'org.apache.logging.log4j.simplelog.StatusLogger.level' to TRACE to show Log4j2 internal initialization logging.

-----Begin installing components-----
VMware Identity Manager
VMware Secure Token Service
Lightwave UI

Begin installing component: vmware-identity-manager
Installed vmware-identity-manager succesfully.

Begin installing component: vmware-secure-token-service
com.vmware.identity.configure.SecureTokenServerInstallerException: Failed to start STS service [error code: 1]
        at com.vmware.identity.configure.SecureTokenServerInstaller.startSTSService(SecureTokenServerInstaller.java:130)
        at com.vmware.identity.configure.SecureTokenServerInstaller.install(SecureTokenServerInstaller.java:93)
        at com.vmware.identity.configure.VMIdentityController.setupInstance(VMIdentityController.java:226)
        at com.vmware.identity.configure.VMIdentityController.setupInstanceStandalone(VMIdentityController.java:52)
        at com.vmware.identity.configure.VMIdentityStandaloneInstaller.main(VMIdentityStandaloneInstaller.java:74)
Failed to start STS service [error code: 1]
vmware-secure-token-service installation failed.
Installation failed.
Errorcode: -1com.vmware.identity.configure.DomainControllerNativeException: com.vmware.identity.configure.SecureTokenServerInstallerException: Failed to start STS service [error code: 1]
        at com.vmware.identity.configure.VMIdentityController.setupInstance(VMIdentityController.java:236)
        at com.vmware.identity.configure.VMIdentityController.setupInstanceStandalone(VMIdentityController.java:52)
        at com.vmware.identity.configure.VMIdentityStandaloneInstaller.main(VMIdentityStandaloneInstaller.java:74)
Caused by: com.vmware.identity.configure.SecureTokenServerInstallerException: Failed to start STS service [error code: 1]
        at com.vmware.identity.configure.SecureTokenServerInstaller.startSTSService(SecureTokenServerInstaller.java:130)
        at com.vmware.identity.configure.SecureTokenServerInstaller.install(SecureTokenServerInstaller.java:93)
        at com.vmware.identity.configure.VMIdentityController.setupInstance(VMIdentityController.java:226)
        ... 2 more
Failed to start Secure Token Service.
Secure Token Service Installation - Failed
ro

**Comment by snambakam** [comment]
Did you follow the instructions at https://github.com/vmware/lightwave/wiki/Configuration-Server-Promote ?

Based on the comment in issue #30 can we assume that this issue is now solved?

Thanks

**Comment by okehariansyah** [comment]
Hi snambakam,

Thank you, this issue is now solved
