### ISSUE TITLE
How to Configure Web Portal for Multitenancy?

### ISSUE THREAD

**Issue by okehariansyah** [vmware/lightwave#30]
Hi,

I had install and promote dc lightwave but i cannot access for web portal multitenancy. how to configure web portal?

Thank you

**Comment by okehariansyah** [comment]
Hi snanbakm,

For this new case, i still cannot access the portal.. have you any solutions?

**Comment by snambakam** [comment]
After running configure-lightwave-server successfully as described in https://github.com/vmware/lightwave/wiki/Configuration-Server-Promote the LightwaveUI should be available at https://<lightwave server hostname or IP>/lightwaveui

If you browse to https://<lightwave server hostname or IP> it should navigate to the Lightwave UI home page for the system tenant.

**Comment by snambakam** [comment]
The OIDC client for Lightwave UI is registered typically using its FQDN which may not be resolvable from the system where the web browser is launched.

Please ensure that the FQDN of the Lightwave Domain Controller is resolvable via DNS from the system where the web browser is launched.

Alternatively, since the Domain Controller is expected to use a static IP, the URL of the OIDC client may be modified to use an IP Address. [Here](https://github.com/vmware/lightwave/wiki/how-to-update-oidc-client-url-address) is some sample code that shows how to update.

**Comment by harishspqr** [comment]
You should be able to open the LDAP directory browser by clicking the "directory" link in the lightwave UI. From there you could view all the tenants from the slider on the right that opens when you click the top right corner of the screen. 

If the FQDN of the lightwave server is not DNS resolvable, an easy workaround would be to add a /etc/hosts entry to map IP to FQDN.

**Comment by okehariansyah** [comment]
Hi snambakam,

Sorry i miscommunication yesterday, im success promotion using http://blog.jreypo.io/cloud-native/devops/vmware/vmware-lightwave-multi-node-domain-setup/ and for today i'm retrying to promote dc using https://github.com/vmware/lightwave/wiki/Configuration-Server-Promote. and error on step -----Checking Certificate service----- 

-----Checking Certificate service-----
Certificate Service checked successfully.
ERROR StatusLogger No log4j2 configuration file found. Using default configurati                                                                                        on: logging only errors to the console. Set system property 'org.apache.logging.                                                                                        log4j.simplelog.StatusLogger.level' to TRACE to show Log4j2 internal initializat                                                                                        ion logging.

-----Begin installing components-----
VMware Identity Manager
VMware Secure Token Service
Lightwave UI

Begin installing component: vmware-identity-manager
Installed vmware-identity-manager succesfully.

Begin installing component: vmware-secure-token-service
com.vmware.identity.configure.SecureTokenServerInstallerException: Failed to sta                                                                                        rt STS service [error code: 1]
        at com.vmware.identity.configure.SecureTokenServerInstaller.startSTSServ                                                                                        ice(SecureTokenServerInstaller.java:130)
        at com.vmware.identity.configure.SecureTokenServerInstaller.install(Secu                                                                                        reTokenServerInstaller.java:93)
        at com.vmware.identity.configure.VMIdentityController.setupInstance(VMId                                                                                        entityController.java:226)
        at com.vmware.identity.configure.VMIdentityController.setupInstanceStand                                                                                        alone(VMIdentityController.java:52)
        at com.vmware.identity.configure.VMIdentityStandaloneInstaller.main(VMId                                                                                        entityStandaloneInstaller.java:74)
Failed to start STS service [error code: 1]
vmware-secure-token-service installation failed.
Installation failed.
Errorcode: -1com.vmware.identity.configure.DomainControllerNativeException: com.                                                                                        vmware.identity.configure.SecureTokenServerInstallerException: Failed to start S                                                                                        TS service [error code: 1]
        at com.vmware.identity.configure.VMIdentityController.setupInstance(VMId                                                                                        entityController.java:236)
        at com.vmware.identity.configure.VMIdentityController.setupInstanceStand                                                                                        alone(VMIdentityController.java:52)
        at com.vmware.identity.configure.VMIdentityStandaloneInstaller.main(VMId                                                                                        entityStandaloneInstaller.java:74)
Caused by: com.vmware.identity.configure.SecureTokenServerInstallerException: Fa                                                                                        iled to start STS service [error code: 1]
        at com.vmware.identity.configure.SecureTokenServerInstaller.startSTSServ                                                                                        ice(SecureTokenServerInstaller.java:130)
        at com.vmware.identity.configure.SecureTokenServerInstaller.install(Secu                                                                                        reTokenServerInstaller.java:93)
        at com.vmware.identity.configure.VMIdentityController.setupInstance(VMId                                                                                        entityController.java:226)
        ... 2 more
Failed to start Secure Token Service.
Secure Token Service Installation - Failed

What can i do?

**Comment by okehariansyah** [comment]
Hi snambakam,

Sorry i miscommunication for yesterday, i had success for promoting DC with /opt/vmware/bin/ic-promote --domain sampledomain.com --password mypassword

But if i configuring DC using /opt/vmware/bin/configure-lightwave-server --domain sampledomain.com --password mypassword still not success. with error : 

-----Checking Certificate service-----
Certificate Service checked successfully.
ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console. Set system property 'org.apache.logging.log4j.simplelog.StatusLogger.level' to TRACE to show Log4j2 internal initialization logging.

-----Begin installing components-----
VMware Identity Manager
VMware Secure Token Service
Lightwave UI

Begin installing component: vmware-identity-manager
Installed vmware-identity-manager succesfully.

Begin installing component: vmware-secure-token-service
com.vmware.identity.configure.SecureTokenServerInstallerException: Failed to start STS service [error code: 1]
        at com.vmware.identity.configure.SecureTokenServerInstaller.startSTSService(SecureTokenServerInstaller.java:130)
        at com.vmware.identity.configure.SecureTokenServerInstaller.install(SecureTokenServerInstaller.java:93)
        at com.vmware.identity.configure.VMIdentityController.setupInstance(VMIdentityController.java:226)
        at com.vmware.identity.configure.VMIdentityController.setupInstanceStandalone(VMIdentityController.java:52)
        at com.vmware.identity.configure.VMIdentityStandaloneInstaller.main(VMIdentityStandaloneInstaller.java:74)
Failed to start STS service [error code: 1]
vmware-secure-token-service installation failed.
Installation failed.
Errorcode: -1com.vmware.identity.configure.DomainControllerNativeException: com.vmware.identity.configure.SecureTokenServerInstallerException: Failed to start STS service [error code: 1]
        at com.vmware.identity.configure.VMIdentityController.setupInstance(VMIdentityController.java:236)
        at com.vmware.identity.configure.VMIdentityController.setupInstanceStandalone(VMIdentityController.java:52)
        at com.vmware.identity.configure.VMIdentityStandaloneInstaller.main(VMIdentityStandaloneInstaller.java:74)
Caused by: com.vmware.identity.configure.SecureTokenServerInstallerException: Failed to start STS service [error code: 1]
        at com.vmware.identity.configure.SecureTokenServerInstaller.startSTSService(SecureTokenServerInstaller.java:130)
        at com.vmware.identity.configure.SecureTokenServerInstaller.install(SecureTokenServerInstaller.java:93)
        at com.vmware.identity.configure.VMIdentityController.setupInstance(VMIdentityController.java:226)
        ... 2 more
Failed to start Secure Token Service.
Secure Token Service Installation - Failed
ro

**Comment by phoenyx762** [comment]
After successful install the UI is not functional with default packages? Is this something that needs to be compiled seperately?
